

environment:
  matrix:
  - GENERATOR: MinGW Makefiles
  # For later use
  #  - GENERATOR: Visual Studio 14 2015
  #  - GENERATOR: Visual Studio 14 2015 Win64

configuration: Debug

install:
  - python.exe -m pip install pytest nose_parameterized

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ..

build_script: cmake --build . --config %CONFIGURATION%

test_script: ctest -V .